import { describe, expect, it } from "vitest";
import { formatUntrustedCommentArtifact } from "../src/publish-comment-file.js";

describe("workflow-run comment publishing", () => {
  it("renders untrusted artifacts as escaped preformatted text", () => {
    const comment = formatUntrustedCommentArtifact(
      "## Result\r\n@maintainer <img src=x> [unsafe](https://example.com)",
    );

    expect(comment).toContain("Generated by the read-only pull request analysis workflow.");
    expect(comment).toContain("&#64;maintainer");
    expect(comment).toContain("&lt;img src=x&gt;");
    expect(comment).not.toContain("@maintainer");
    expect(comment).not.toContain("<img src=x>");
  });

  it("truncates oversized artifacts before publishing", () => {
    const comment = formatUntrustedCommentArtifact("x".repeat(60_000));

    expect(comment).toContain("Output truncated before publishing.");
    expect(comment.length).toBeLessThan(51_000);
  });
});
